# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LGADMeasurement_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(703, 403)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(30, 40, 641, 301))
        self.tabWidget.setObjectName("tabWidget")
        self.tabIV = QtWidgets.QWidget()
        self.tabIV.setObjectName("tabIV")
        self.groupBoxIV = QtWidgets.QGroupBox(self.tabIV)
        self.groupBoxIV.setGeometry(QtCore.QRect(0, 20, 621, 211))
        self.groupBoxIV.setObjectName("groupBoxIV")
        self.layoutWidget = QtWidgets.QWidget(self.groupBoxIV)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 40, 531, 136))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.lineEditSensorName = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditSensorName.setObjectName("lineEditSensorName")
        self.horizontalLayout_4.addWidget(self.lineEditSensorName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEditInitialVoltage = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditInitialVoltage.setObjectName("lineEditInitialVoltage")
        self.horizontalLayout_2.addWidget(self.lineEditInitialVoltage)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEditFinalVoltage = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditFinalVoltage.setObjectName("lineEditFinalVoltage")
        self.horizontalLayout_2.addWidget(self.lineEditFinalVoltage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBoxReturnSweep = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBoxReturnSweep.setObjectName("checkBoxReturnSweep")
        self.horizontalLayout_3.addWidget(self.checkBoxReturnSweep)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.checkBoxLivePlot = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBoxLivePlot.setObjectName("checkBoxLivePlot")
        self.horizontalLayout_3.addWidget(self.checkBoxLivePlot)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.pushButtonStartMeasurement = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonStartMeasurement.setObjectName("pushButtonStartMeasurement")
        self.verticalLayout_2.addWidget(self.pushButtonStartMeasurement)
        self.tabWidget.addTab(self.tabIV, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBoxIV.setTitle(_translate("Dialog", "IV measurement"))
        self.label_3.setText(_translate("Dialog", "Sensor Name"))
        self.label.setText(_translate("Dialog", "Initial Voltage (V)"))
        self.label_2.setText(_translate("Dialog", "Final Voltag (V)"))
        self.checkBoxReturnSweep.setText(_translate("Dialog", "Return Sweep"))
        self.checkBoxLivePlot.setText(_translate("Dialog", "Live Plot"))
        self.pushButtonStartMeasurement.setText(_translate("Dialog", "Start Measurement"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIV), _translate("Dialog", "IV setup"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "CV setup"))
